name: Update recent activity

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Update activity section in README
        uses: jamesgeorge007/github-activity-readme@master
        with:
          COMMIT_MSG: "chore: update recent activity"
          MAX_LINES: 6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
